<a href="https://colab.research.google.com/github/jayarnim/study-RBasicSyntax/blob/main/2_Data_Structure_1_Singlular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. 단일집합자료형(Singular Data Sturcture)

- 정의
    - 원소의 자료형이 단일로 통일되어 있는 집합자료형
    - 통일되어 있지 않을 경우 우선순위에 따라 원소에 대하여 강제 형변환함
        - 우선순위 : 문자형, 숫자형, 논리형 순
    - 원소로 집합자료형을 할당하는 경우 강제 Unpacking 함

- 종류
    - 벡터(Vector) : 1차원 단일집합자료형
    - 팩터(Factor) : 범주형 자료를 다루는 1차원 단일집합자료형, 혹은 그러한 범주
    - 행렬(Matrix) : 2차원 단일집합자료형
    - 배열(Array) : n차원 단일집합자료형

# 1. Vector

## 벡터 생성하기

### combine 함수

In [1]:
xs1 <- c(1, 5, 7)
xs1

[1] 1 5 7

In [2]:
xs2 <- c(1:8)
xs2

[1] 1 2 3 4 5 6 7 8

### sequence 함수

In [3]:
xs3 <- seq(1, 50, by = 3)
xs3

[1]  1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49

## Keyword Mapping

In [4]:
ks <- c("태연", "써니", "티파니", "효연", "유리", "수영", "윤아", "서현")
ks_keyword <- c("메인보컬", "리드보컬", "리드보컬", "메인댄서", "리드댄서", "리드댄서", "센터", "리드보컬")

In [5]:
# 벡터 ks1 에 벡터 ks2 를 keyword mapping
names(ks) <- ks_keyword

In [6]:
# ks 조회
ks

메인보컬 리드보컬 리드보컬 메인댄서 리드댄서 리드댄서     센터 리드보컬 
  "태연"   "써니" "티파니"   "효연"   "유리"   "수영"   "윤아"   "서현"

In [7]:
# ks names 조회
names(ks)

[1] "메인보컬" "리드보컬" "리드보컬" "메인댄서" "리드댄서" "리드댄서" "센터"    
[8] "리드보컬"

## 벡터 탐색하기

In [8]:
# reps = c(1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4)
reps <- rep(c(1:4), times = 4)

### 자료 형상

In [9]:
str(reps)

 int [1:16] 1 2 3 4 1 2 3 4 1 2 ...


### 자료 클래스

In [10]:
class(reps)

[1] "integer"

### 원소 자료형

In [11]:
mode(reps)

[1] "numeric"

In [12]:
typeof(reps)

[1] "integer"

### 원소 갯수

In [13]:
length(ks)

[1] 8

### Unique Value

In [14]:
unique(reps)

[1] 1 2 3 4

## Indexing

### With Index

In [15]:
ks[2]

리드보컬 
  "써니"

In [16]:
ks[[2]]

[1] "써니"

### With Keyword

In [17]:
ks["메인보컬"]

메인보컬 
  "태연"

In [18]:
ks[["메인보컬"]]

[1] "태연"

In [19]:
# keyword 가 여러 개 사용되는 경우 가장 먼저 mapping 된 value 를 가져옴
ks["리드보컬"]

리드보컬 
  "써니"

### Slicing

In [20]:
ks[2:6]

리드보컬 리드보컬 메인댄서 리드댄서 리드댄서 
  "써니" "티파니"   "효연"   "유리"   "수영"

In [21]:
ks[c(2, 4, 6)]

리드보컬 메인댄서 리드댄서 
  "써니"   "효연"   "수영"

In [22]:
# 슬라이싱의 경우 인덱싱과 달리 value 만 단독으로 가져올 수 없음
# ks[[2, 4, 6]]

# 3. Matrix

In [23]:
gg <- c("태연", "서현", "티파니", "써니", "효연", "유리", "수영", "윤아")
gg_num <- c(1:8)

## 행렬 생성하기

### matrix 함수

```
matrix(
    data,
    nrow,
    ncol,
    byrow = FALSE,
    dimnames
    )
```

- `nrow` : 주어진 자료를 설정한 행 갯수로 나누어 행 순서로 배열함

In [24]:
ex1_mat1 <- matrix(
    gg,
    nrow = 2
    )

View(ex1_mat1)

[,1] [,2]   [,3] [,4]
[1,] 태연 티파니 효연 수영
[2,] 서현 써니   유리 윤아

- `ncol` : 열 갯수

In [25]:
ex1_mat2 <- matrix(
    gg,
    ncol = 2
    )

View(ex1_mat2)

[,1]   [,2]
[1,] 태연   효연
[2,] 서현   유리
[3,] 티파니 수영
[4,] 써니   윤아

- `byrow = FALSE` : 행을 기준으로 채워넣을 것인가

In [26]:
ex1_mat3 <- matrix(
    gg,
    ncol = 2,
    byrow = FALSE
    )

View(ex1_mat3)

[,1]   [,2]
[1,] 태연   효연
[2,] 서현   유리
[3,] 티파니 수영
[4,] 써니   윤아

In [27]:
ex1_mat4 <- matrix(
    gg,
    ncol = 2,
    byrow = TRUE
    )

View(ex1_mat4)

[,1]   [,2]
[1,] 태연   서현
[2,] 티파니 써니
[3,] 효연   유리
[4,] 수영   윤아

- `dimnames` : 행 이름, 열 이름 설정

In [28]:
ex1_mat5 <- matrix(
    gg,
    ncol = 2,
    byrow = FALSE,
    dimnames = list(c(1:4), c("보컬", "댄서"))
    )

View(ex1_mat5)

보컬   댄서
1 태연   효연
2 서현   유리
3 티파니 수영
4 써니   윤아

### 벡터 결합

In [29]:
# 행 기준 결합
ex2_mat1 <- rbind(gg, gg_num)
View(ex2_mat1)

[,1] [,2] [,3]   [,4] [,5] [,6] [,7] [,8]
gg     태연 서현 티파니 써니 효연 유리 수영 윤아
gg_num 1    2    3      4    5    6    7    8

In [30]:
# 열 기준 결합
ex2_mat2 <- cbind(gg, gg_num)
View(ex2_mat2)

gg     gg_num
[1,] 태연   1     
[2,] 서현   2     
[3,] 티파니 3     
[4,] 써니   4     
[5,] 효연   5     
[6,] 유리   6     
[7,] 수영   7     
[8,] 윤아   8

## 행렬 탐색하기

In [31]:
ex3_mat <- cbind(gg, gg_num)
View(ex3_mat)

gg     gg_num
[1,] 태연   1     
[2,] 서현   2     
[3,] 티파니 3     
[4,] 써니   4     
[5,] 효연   5     
[6,] 유리   6     
[7,] 수영   7     
[8,] 윤아   8

### 자료 형상

In [32]:
str(ex3_mat)

 chr [1:8, 1:2] "태연" "서현" "티파니" "써니" "효연" "유리" "수영" "윤아" ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:2] "gg" "gg_num"


### 자료 클래스

In [33]:
class(ex3_mat)

[1] "matrix" "array"

### 원소 자료형

In [34]:
mode(ex3_mat)

[1] "character"

In [35]:
typeof(ex3_mat)

[1] "character"

### 행, 열 이름

In [36]:
# 행 이름, 열 이름 모두 탐색
dimnames(ex3_mat)

[[1]]
NULL

[[2]]
[1] "gg"     "gg_num"

In [37]:
# 행 이름만 탐색
rownames(ex3_mat)

NULL

In [38]:
# 열 이름만 탐색
colnames(ex3_mat)

[1] "gg"     "gg_num"

### 크기

In [39]:
# 차원 탐색
dim(ex3_mat)

[1] 8 2

In [40]:
# 행 갯수 탐색
nrow(ex3_mat)

[1] 8

In [41]:
# 열 갯수 탐색
ncol(ex3_mat)

[1] 2

In [42]:
# 원소 갯수 탐색
length(ex3_mat)

[1] 16

## Indexing

In [43]:
ex4_mat <- matrix(
    gg,
    nrow = 2
    )

In [44]:
# [행 번호, 열 번호] 혹은 [행 이름, 열 이름]을 통해 해당 자리에 위치한 원소를 masking 함
ex4_mat[1, 1]

[1] "태연"

In [45]:
# 여러 원소를 masking 하고 싶은 경우
ex4_mat[1, 1:3]
ex4_mat[1, c(1, 3)]

[1] "태연"   "티파니" "효연"

[1] "태연" "효연"

## 행렬 연산

### 원소 간 대표값 집계

In [46]:
ex5_mat1 <- matrix(c(1:25), ncol = 5)

In [47]:
# 행별 평균
rowMeans(ex5_mat1)

[1] 11 12 13 14 15

In [48]:
# 열별 평균
colMeans(ex5_mat1)

[1]  3  8 13 18 23

### Matrix & Scala

- 행렬의 각 원소에 대하여 스칼라만큼 연산함

In [49]:
ex5_mat2 <- matrix(c(1:4), ncol = 2)

In [50]:
# 덧셈
ex5_mat2 + 2

[,1] [,2]
[1,] 3    5   
[2,] 4    6

In [51]:
# 뺄셈
ex5_mat2 - 2

[,1] [,2]
[1,] -1   1   
[2,]  0   2

In [52]:
# 곱셈
ex5_mat2 * 10

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [53]:
# 나눗셈
ex5_mat2 / 10

[,1] [,2]
[1,] 0.1  0.3 
[2,] 0.2  0.4

### Matrix & Matrix

In [54]:
ex5_mat3_1 <- matrix(c(1:6), ncol = 2)
ex5_mat3_2 <- matrix(c(11:16), ncol = 2)
ex5_mat3_3 <- matrix(c(1:6), nrow = 2)

#### 덧셈과 뺄셈

- 조건 : 피연산자 A, B는 차원이 같음

In [55]:
# 차원이 같은 경우
ex5_mat3_1 + ex5_mat3_2

[,1] [,2]
[1,] 12   18  
[2,] 14   20  
[3,] 16   22

In [56]:
# 차원이 다른 경우
# ex5_mat3_1 - ex5_mat3_3

#### 내적

- 조건 : 피연산자 A, B는 적합성 조건을 만족함

In [57]:
# 적합성 조건을 만족하는 경우
ex5_mat3_1 %*% ex5_mat3_3

[,1] [,2] [,3]
[1,]  9   19   29  
[2,] 12   26   40  
[3,] 15   33   51

In [59]:
# 적합성 조건을 만족하지 않는 경우
# ex5_mat3_1 %*% ex5_mat3_2

## 특수한 행렬 생성하기

### 대각행렬

In [60]:
# diag(x1, x2, ..., xn) : 대각원소가 x1, x2, ..., xn인 n차원 정방행렬을 생성함
ex3_mat1 <- diag(c(1:3))
View(ex3_mat1)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

### 삼각행렬

In [61]:
# lower.tri(ex_mat) : 정방행렬 ex_mat 의 하삼각원소들을 masking 함
ex3_mat2 <- matrix(c(1:16), ncol = 4)
ex3_mat2[lower.tri(ex3_mat2, diag = TRUE)] <- 0
View(ex3_mat2)

[,1] [,2] [,3] [,4]
[1,] 0    5     9   13  
[2,] 0    0    10   14  
[3,] 0    0     0   15  
[4,] 0    0     0    0

In [62]:
# upper.tri(ex_mat) : 정방행렬 ex_mat 의 상삼각원소들을 masking 함
ex3_mat3 <- matrix(c(1:16), ncol = 4)
ex3_mat3[upper.tri(ex3_mat3, diag = TRUE)] <- 0
View(ex3_mat3)

[,1] [,2] [,3] [,4]
[1,] 0    0     0   0   
[2,] 2    0     0   0   
[3,] 3    7     0   0   
[4,] 4    8    12   0

### 역행렬

In [74]:
# solve(A, B) : 가역성을 가지는 두 행렬 A, B에 대하여, A * X = B 를 충족하는 행렬 X를 구함
# B를 할당하지 않을 경우 A의 역행렬을 구함
solve(matrix(c(1, 2, 6, -1), ncol = 2))

[,1]       [,2]       
[1,] 0.07692308  0.46153846
[2,] 0.15384615 -0.07692308

### 전치행렬

In [69]:
t(matrix(c(1:16), ncol = 4))

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

# 4. Array

## 배열 생성하기

### array 함수

```
array(
    data,
    dim = c(nrow, ncol, nchannel)
    )
```

In [76]:
View(
    array(
        c(1:6),
        dim = c(2, 3, 4))
    )

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 3

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 4

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6